### ISSUE TITLE
Any CI textfield

### ISSUE THREAD

**Issue by gfmoore** [gfmoore/ESCI-JS#1]
There is a field ready for allowing any confidence interval to be entered. Enable this. If a user click on the drop down option it clears the text field and uses the selected option.

**Comment by gdcumming** [comment]
Gordon, I've had a rethink about my earlier request that a user be able to type in any value for N, and for C (% for a CI). The drop down menus with fixed choices are quick and easy to use. On any touch device it's a pain to have to type in anything, even a number. 

In asking for choices by typing in, I had in mind experimenting with N= very small, when seeing how the central limit worked, and how surprisingly fast the mean heap approaches normal in shape as N gets a bit bigger. But even for this we don't need more than a few small options for N. So let's drop the type-in option?

Maybe for N we would be in great shape with options, e.g.
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 20, 25, 30, 40, 50, 60, 80, 100

For C I'm actually keen that folks use 95 all the while, unless there are very strong reasons contra in a particular situation. Maybe offer:
50, 68 [i.e. approx same as SE for means, N not small], 80, 90, 95, 98, 99, 99.8, 99.9
[98 corresponding to one-tail 99, 99.8 the same for 99.9]

...assuming that having so many options in a drop-down does not create problems.
Geoff

**Comment by gfmoore** [comment]
This is fine, and implemented.

**Comment by gdcumming** [comment]
Thanks, looks good. Any particular reason you chose to omit 50 and 68 for C?

**Comment by gdcumming** [comment]
I  was checking how it deals with the new N=1, using 'Take Sample' repeatedly. No CI when sigma not known, very long CI when sigma known. Good behaviour for N = 2 and 7. Sweet! Then I tried 'Run' and found dropping means stopped after a small (and variable) number of samples. Also for N = 3, 4, 6, 7, 8, 9, 12.... 80, so maybe for the new values of N added in this version.

**Comment by gfmoore** [comment]
No reason, except I missed them (50,68) - oops.

I couldn't replicate the dropping means actually stopping, but I did notice that the number of samples didn't correspond to the N selected. This was my fault as though I had put in the correct numbers I had adjusted the value attribute - schoolboy error. Fixed.

It seems to run okay for me, Could you test the dropping means issue again please. How long are we talking 10s of drops, 100s, more? 

For a sample of 1
When sigma is known then CI will be M +/- 1.96 x sigma   (if 95% CI)
When sigma is unknown, then what is s for a sample of 1? There is no deviation from sample mean, so should be 0 and therefore the CI is M+/- 0  so no tails.  Of course the sample sd is dividing by 0 as well. i.e. (n-1)
Have I got this wrong? Probably :)

**Comment by gdcumming** [comment]
This morning I seemed to be getting the stop-the-drop means only for N=1. So I rebooted the computer, reloaded 0.3.6 version, and started exploring. With N=1 pretty much always I would get a couple or a dozen or a few dozen dropping means into the pile, then the dropping means stopped--no more added to the pile, while sampling continued--I would see the dancing data points for successive samples, and the counts of samples taken kept climbing, just no dropping means.

I found that it sometimes happened for N=2. But *never* for rectangular pop shape. Aha, so try normal pop with sigma = max = 50. Then it happened even for larger N, rarely for N above 20. Didn't matter whether new (eg 6) or old (eg 5) value of N. Always for N=1, progressively less often for progressively higher values of N. Very irregular as to how many means dropped before they stopped. Maybe the stop is triggered by a mean (or a data value) being outside (0, 100)? Or the mean or a data value extreme in some other way?

I tried normal pop, mu = 80 (the max) and sigma = 50. First run with N=60 stopped dropping at around 700 samples. I tried typing in even more extreme values for mu and sigma (beyond the limits of the sliders). Pop curve seemed to change appropriately. With mu = 20, sigma = 80, N = 100, stop after about 80 samples. All of which is consistent with the hypothesis that the drop is triggered by some extreme value happening.

Happens also on iPad and iPhone. 

Incidentally, the version number (in front of the icon) does not hide on those i- devices. Also on big screen, often the version number appears then hides very nicely on a short hover of the mouse, but sometimes doesn't hide--until you take the mouse back there or in some other way give it a jolt.

For stop-the-drop, I could try making a video or two if that might help.

**Comment by gfmoore** [comment]
Ok, I've had a look and you were spot on. The issue is caused by a sample mean being less than zero or greater than 100 and is causing a failure to index into the heap - negative index or index greater than array size. 

However, a simple fix of if (xmean < 0) xmean = 0 etc doesn't really solve the issue as it just means that the heap starts to pile up at 0 and 100 (more than what I might have thought.)

I'll upload the temporary fix so you can see (0.3.8). I guess it will happen more often for sample size of 1. (I haven't extensively tested this fix btw, so... Don't forget to clear the browser cache if you don't see 0.3.8 !!!

By the way have you noted how the speed really starts to slow down after many hundred samples. Made me think that perhaps the memory in tablets/phones may become a limiting factor? Anyway, I'll put that issue on the back burner for now.

So I/we need to think about what should happen if a sample mean is outside the viewable limits, i.e. less than 0 or greater than 100.

I'm well impressed how you figured out the problem, it really helped me focus on the area of code.

:)

**Comment by gdcumming** [comment]
Excellent--hey, what a team! Yep, I can see the means piling at 0, 100, for N=1, large sigma.

That seems to me no solution. If C% capture is to be achieved in the long run, our calcs need to accord with our statistical model, e.g. normal distribution, random sampling...  No truncation permitted, or our empirical demos of capture %ages will fail. For any data point outside (0, 100) we need to use the value of that point in calcs of sample mean and SD, even if the value is -5.73 or +111.1, etc.

But for storage of sample info you need only store sample mean and SD, for every sample in a run? To save recalculation, you could also store MoE, but that would be for a specific C, so we would need to recalc MoE (from the stored sample SD) if C is changed (and sigma still unknown). I.e. no need to store the value of every data point in every sample--just use those once to get mean and SD for storage. Those stored means and SDs can have any value, no limit to (0, 100). Maybe that's what you do already, in which case I didn't follow your comment about failure to index into the heap.

Any data point, or any sample mean that falls outside (0, 100) is simply not displayed, but is still counted as present for all the counts and %capture values that are reported. If a sample mean is off-screen, we may still see part of the CI on that mean--which we can think of as off-screen to L or R. I hope the display software permits that to work automatically, without any added complexity for the programming. In fact I think it does--for N=2, sigma = 50, take single samples, and see red and green, part CIs (with mean off-screen), and what seems like correct counting of samples taken, number and % capturing. It's only the display of means that's distorted by piles at 0 and 100. Simply (?) don't display means that should be off-screen.

Suddenly a bit alarmed, I've gone back to ESCI CI-jumping, and am relieved to see that it does behave like that. Use sigma=50, N=2, show CIs, then samples with point and/or mean off-screen do behave well. Part CIs are visible, and capture (green or red), and correct counting of capture for the Capture% all seem to behave correctly. Phew!

**Comment by gfmoore** [comment]
Yes, you are right. I need to think about what my code is doing :) 
I'll have a look tomorrow and try and re-trace exactly what my logic is - I'm getting so senile I forget. :)
I think the main issue is just with adding to the heap and if outside the visible window I can just ignore trying to add to the visible part of the heap. yet another if statement and flag! lol

**Comment by gdcumming** [comment]
I guess the main thing about means that are not displayed, while dropping and in the heap, is that they get counted, and get included in the calc of the mean of the heap, and SE heap, i.e. SD of all means in the heap.

**Comment by gfmoore** [comment]
I think I've now fixed the code so that means outside the viewing area do not get displayed, but are still included in the stats (as they already were). If the heap is visible they do not affect the heap. In effect they drop to the bottom of the unseen part of the display and are then removed as for any other sample mean.

**Comment by gdcumming** [comment]
I've played a bit, and calculated a few heap mean and sd values. All seems well. So I'll close this issue, for now at least!
Did I mention how wonderfully neat and beautiful the stacking is of means in the heap?

**Comment by gdcumming** [comment]
Hmmm. I can't see how to close this issue. Maybe I can't, because you created it.

**Comment by gfmoore** [comment]
Yay, closing closing closed. 

Feel free to reopen ;)
