### ISSUE TITLE
Outrageous suggestion, app version

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#13]
An app version? 

On the phone, for example, I guess the LH panel would need to be summoned as an overlay when needed, then hidden, so the RH panel could take the whole screen area, with, say, a single line of icons across the bottom: maybe the three buttons, plus CI show/hide, sigma known/unknown, capture/no-capture. 

Are apps built in some form of java, or something else entirely? (Pls excuse my complete novice status here.) Folks sitting on the train could be mindlessly gazing at some statistical dance, while enjoying their choice of music. Thesis topic: how much improvement in their intuitions about the extent of sampling variability might doing this produce?!

**Comment by gfmoore** [comment]
As agreed? we'll close this for now. When I get time I'll look into Electron (I did purchase a Udemy course some time ago and never followed through.)
