### ISSUE TITLE
Add link to thenewstatistics.com

### ISSUE THREAD

**Issue by rcalinjageman** [gfmoore/ESCI-JS#16]
I was wondering if it might be a good idea to have a link or top-level menu item to thenewstatistics.com.  I'd like to link the current blog to this new dance of the means, and want to also be able to have them come back to the blog after the dance.  Not essential; just a suggestion.

**Comment by gfmoore** [comment]
Do you mean on the app itself? If so, Where would be a good place? at the bottom as a footer? or at the top. 
What is the url you would like to use?
Let me know and it shall be done 😀

**Comment by gfmoore** [comment]
Any further thoughts on this, I'd like to get it closed please. Just need a url and a position. :)

**Comment by gdcumming** [comment]
Bob,
#16 -- this one for you
G

--------------------------------------------
Geoff Cumming, DPhil, Emeritus Professor,
School of Psychology and Public Health, La Trobe University, Melbourne Campus, Victoria, Australia 3086
Email: g.cumming@latrobe.edu.au<mailto:g.cumming@latrobe.edu.au>
Intro textbook: Introduction to The New Statistics: Estimation, Open Science, and Beyond    www.thenewstatistics.com<http://www.thenewstatistics.com>
First book: Understanding The New Statistics: Effect Sizes, Confidence Intervals, and Meta-Analysis   ww.thenewstatistics.com<http://www.thenewstatistics.com/>
Own page: http://www.latrobe.edu.au/she/contact-us/staff/profile?uname=GDCumming
ESCI (Exploratory Software for Confidence Intervals):  www.thenewstatistics.com<http://www.thenewstatistics.com/>
Introduction to the New Statistics is the first statistics textbook to focus on Open Science and the New Statistics. Instructors can obtain a free desk copy at https://www.routledge.com/resources/deskcopy.
Order on Amazon <http://www.amazon.com/dp/1138825522>
[1464879986726_ITNS]


________________________________

**Comment by rcalinjageman** [comment]
Anywhere the seems reasonable is good (a thin banner at the top?  a thin banner at the bottom?)
Url should be https://thenewstatistics.com/

**Comment by gfmoore** [comment]
Implemented at the bottom as a footer.

Can this be closed perhaps?

**Comment by gfmoore** [comment]
Hope you don't mind, but I closed this. Re-open if not happy :)
