### ISSUE TITLE
Rectangular (i.e. uniform) distribution

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#18]
0.3.28
Something funny going on. I noticed that capture % of CIs, sigma known, is often 100% or very close.

Then I noticed that the SD lines for a rectangular pop are displayed at the two ends of the rectangle. 

In fact, if a and b are the two ends of the rectangle, then 

SD = (b - a) / SQRT(12)

Or, if mu and sigma are specified, and we want to find the end points of the rectangle (mu +/- c) then:

sigma = 2c / SQRT(12), and so c = SQRT(3) * sigma

i.e. ends are mu +/- SQRT(3) * sigma

I wonder whether changing that might change how CI capture, sigma known, might behave?

Another small point (not worth a separate issue): Value of 'MoE population' can be displayed as soon as a pop (and N) is specified i.e. any time. Only 'MoE sample' needs to wait until a sample is taken.

**Comment by gfmoore** [comment]
Ahhh, I didn't know that. Never even thought about it. Thanks. Will make the change(s)

**Comment by gfmoore** [comment]
Okay I think I've implemented the correct width of rectangle
Also implemented the MoE value as soon as population specified. Hope I got it right.

**Comment by gdcumming** [comment]
0.3.30

It looks great. Yep, MoE pop value looks good.

I have done just a couple of not-so-long runs and did get very close to 95% capture. So that's great.

Closing...
