### ISSUE TITLE
software licencing

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#2]
Gordon,
In any ESCI file, first sheet ("Intro"), scroll down to see the licence:

GNU General Public LIcence
Version 3, 29 June 2007.

As I understand it, this protects the developers, while allowing anyone to do anything reasonable with the software. I haven't looked to see what might have happened since 2007.

This looked to me to be reasonable, but I'm still a newbie in this area, and I haven't sought any up-to-date expert advice. Or even done any online searching.

Geoff

**Comment by gfmoore** [comment]
Files updated to reflect this.
