### ISSUE TITLE
Capture of the next mean, Panel 8

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#20]
The idea is that one way to think of a 95% CI is as a prediction interval for where a replication mean will fall, i.e. the mean from a replication study that is exactly like ours, but with a new random sample. In our simulation, the next mean is the one just above a CI in the dance. What is the chance that the next mean falls within our CI? It has to be less than 95% because there is sampling variability (a bit of dancing) in both our mean+CI, AND in the next mean+CI.

It turns out that, in the long run, a 95% CI will on average capture the next mean on 83% of occasions. (I can send a couple of papers, if you like. In one we survey researchers and find that most expect that capture % to be about 95%. No doubt a question that they are highly unlikely to have encountered, or have thought about before.)

But it is handy to be able to think about a 95% CI not just as an interval that 'most likely includes the true value', but also as indicating where, most likely, the mean of a close replication study will fall. (Second 'most likely' is less than the first!)

See CI jumping in ESCI, bottom box at red 8. Turn on 'capture of next mean' and see a pink line from the end of our CI up to the next mean just in those cases where our CI does NOT capture that next mean. So we expect to see such lines in about 17% of cases.

As in ESCI, I think we should allow both 'capture of mu' and 'capture of next mean' to be turned on at once. Which would give coloured means+CIs, and also pink lines where next mean isn't captured by a CI. Both capture %ages would be calculated and displayed.

In calculating the % for capture of next mean, note that the denominator is one less than the number of samples taken so far. (Capture is not possible until we have at least two samples taken. The denominator is the number of successive pairs in the run.)

Not urgent!

**Comment by gfmoore** [comment]
This is very interesting. I will do it. But I need to get what we have settled please. As soon as I do another things lots of other things seem to fall apart - my bad design, but I never thought it would get this complex.

**Comment by gdcumming** [comment]
I agree that it's interesting. A very neat and different way to think about a CI, imho. I suspect it aligns quite well with one way a layperson might think about a margin of error. For example (from our chapter 1), a poll is reported in the news to have found support for the PM is 35% with margin of error of 2. If someone wonders what's likely to happen in another very similar poll, taken at about the same time, but asking a different sample of people, then it's natural to expect the next result should, most likely, fall inside 35 +/- 2%. I.e. thinking of a CI as a prediction interval, without needing to use those fancy terms.

By all means, put this low down the list. Definitely not urgent. Yes, let's get core business sorted. Getting very close now I think.

**Comment by gfmoore** [comment]
Had a first go at implementing this. Getting about 83% after a 1000 samples. I was quite surprised that this happens for sigma unknown as well. So yes I'd like to look at the papers please.

I guess I need to know what conditions will allow display of this feature, So far I've got CIs must be checked. 

There may be bugs (or dragons) here!  :)

**Comment by gdcumming** [comment]
0.3.42

So good to see!

I'll explore some more and report. Need to tie in the logic with whatever we decide for CIs, capture, forcing 'Clear' etc.

Note that for dance of the p values, sound should turn off when either of those checkboxes is cleared. I was surprised when I heard sounds when sampling when dance p cleared (and sound box had auto-cleared).

**Comment by gfmoore** [comment]
I was surprised when I heard sounds when sampling when dance p cleared (and sound box had auto-cleared).

>> :laughing, I bet you were!  Sorry, my mistake, fixed the code so that when dance of p values cleared the flag for sound is also cleared and not just the checkbox.

**Comment by gdcumming** [comment]
0.3.48

So nice to play with this! I think you have close to nailed it, first up :-)

I have run around 10 simulations, 10,000 samples in each. N=2, 5, 10, 20, and 50, 80, and 95 C%. In every case the % capture of next mean has been very or sufficiently close to the expected values in the 2006 article with Robert Maillardet. For both sigma known and unknown! That's pretty strong evidence that (1) you are using a decent random number generator, and (2) your calcs and logic are correct. Great!

With large numbers of samples, the pink diagonal lines pile up at the top of the screen, i.e. are not cleared as their samples pile up on the mean heap, as it spills above the display area.

In Panel 8 can we have 'Number of next means' and a value, inserted above 'Number capturing...'? (Will be one less than number of samples taken--which is not displayed if Capture of mu is off) 

It's good that Panel 8 collapses, and only expands when clicked on. 

It's good that clicking 'Capture of next mean' either on or off causes SCA.

Clicking CIs off and on while 'Capture of next mean' is on can trick it--I think the counting doesn't always match what's on screen. Probably best would be to make turning 'CIs' off (when 'Capture of next mean' is on) do a full SCA, which will also set the values in Panel 8 all to zero.

There may be something to tweak in relation to switching 'Capture of mu' on and off, but I'm hoping that will solve itself after the requested updates to the logic for that critical checkbox, in earlier comment, to #17 I think.

**Comment by gfmoore** [comment]
In Panel 8 can we have 'Number of next means' and a value, inserted above 'Number capturing...'? (Will be one less than number of samples taken--which is not displayed if Capture of mu is off)

>> Implemented.

**Comment by gfmoore** [comment]
There may be something to tweak in relation to switching 'Capture of mu' on and off, but I'm hoping that will solve itself after the requested updates to the logic for that critical checkbox, in earlier comment, to #17 I think.

>> I'm leaving this for now. I can't follow my logic anymore. I could add stop clear action, but hey all anyone has to do is hit the checkbox and it disappears.

**Comment by gdcumming** [comment]
0.3.64

Thanks for extra count.

We still have the issue that, in a long run, when the mean heap climbs beyond the top of the display area, the pink lines pile up at the top of that area, instead of disappearing off-screen with the CIs they were attached to.

This is such a pleasure to watch running.

**Comment by gfmoore** [comment]
Well, that was a hard bug to try and track down, spent the last two days on it (not 48 hours I hasten to add.)

The issue, fwiw is that you need two means to make the link, but when a new mean is produced then if the previous mean (for which I already record the data) id captured as part of the heap, then of course there is no mean to check against. So I eventually found a way to determine if the mean had been captured and not display the magenta lines. I still count it though. 

Hopefully, nothing should have changed the counting, but I guess you'll see it if it has :)

I did find a place where that heap location change we made hadn't been replicated, I didn't even know there were two places, anyway I also updated that, so the heap binning should at least be consistent. But again you might just want to check it.

**Comment by gdcumming** [comment]
0.3.65

Oh dear, sorry that was a hassle. I vaguely recall, way back, that it was tricky getting those captures and counts and displays all correct. So well done.

The counting and % seem fine to me.

I've done a bit of testing of the mean heap piling up, and I don't see any consistent L or R bias. Again, good.

One tiny thing: let's have the default being that Panel 8 is off.

Closing...
