### ISSUE TITLE
Fill population curves is slow.

### ISSUE THREAD

**Issue by gfmoore** [gfmoore/ESCI-JS#22]
As subject.

**Comment by gdcumming** [comment]
Not sure what to suggest. Reduce number of circles in the fill? Store the current fill with the current curve, so don't need to generate it again if curve or fill is clicked on or off? Don't generate a new fill whenever do a 'Clear'. Examine code, esp. the subroutine or loop that is called most often--any way to streamline this? Write some out as linear code rather than nested loops or subroutines? (Talk about the novice making obvious suggestions to the expert...!)

**Comment by gfmoore** [comment]
Okay, so firstly I've gone through the logic. I did find that under certain conditions and due to certain events I was calling the fill population method more than once. This is often what happens as you try to deal with one situation, e.g. vertical or horizontal resize, you add some calls and then before you know it you have spaghetti. (GOTO considered harmful said Dijkstra - same with method calling.)

Also for Skew and custom I might call the fill (without drawing the bubbles) to do the MonteCarlo calcs of mu and sigma, but then call it again if I actually wanted a fill. Anyway this redundancy has been sorted.

So the main issue now is that the bubbles array can hold 50 x the pixel width of points. easily 30k or more. (Not all get displayed because otherwise the bubble having a radius overfills the curve. 

When I've reduced this, even by 10 times the filling looks spotty. Let me demonstrate:
Here first is the skew (for 0.1) filled with the displayable points (those not displayed are still in the array)

![image](https://user-images.githubusercontent.com/22768967/86925653-0a5e6600-c129-11ea-9deb-5ab54b09bb65.png)

The array contains 10895 points,  the picture contains 9822 points. I think this is a reasonable fill (like I said the cosmic background radiation!) The scale factor is 50 x width
The mu was estimated as 50.67 and the sigma as 15.32 

This is 10 times less, 5 x width
![image](https://user-images.githubusercontent.com/22768967/86925942-632dfe80-c129-11ea-9977-011739188d45.png)

The array contains 1080 and the display 971 points
The mu was estimated as  50.49 and the sigma as 15.13

Just for a laugh I did 10 times the first one. (it took a while) 500 x width
![image](https://user-images.githubusercontent.com/22768967/86926311-cfa8fd80-c129-11ea-9ddf-78769b684de3.png)

The array contains 107709 and the display 97069 points
The mu was estimated as  50.58 and the sigma as 15.23

Now going back to the one I'm using as my baseline, here are the pics 
![image](https://user-images.githubusercontent.com/22768967/86926632-375f4880-c12a-11ea-8bc8-9a6388f4cc60.png)

10 times less
![image](https://user-images.githubusercontent.com/22768967/86926710-4e059f80-c12a-11ea-96f0-5dcf05840fac.png)

and 10 times more than the original
![image](https://user-images.githubusercontent.com/22768967/86926818-7097b880-c12a-11ea-85ee-a2ca9a0b74c6.png)

(Actually this last one surprised me, but of course there are lots of bubbles lying over each other.

Just to investigate this further I did the original divided by 2  25 x width
![image](https://user-images.githubusercontent.com/22768967/86927006-af2d7300-c12a-11ea-9950-24cb3d34992f.png)

mean was 50.38 and sigma = 15.17

and divided by 4   12.5 x width
![image](https://user-images.githubusercontent.com/22768967/86927159-e00da800-c12a-11ea-9a3c-ac7f6ffa6313.png)

mean was 50.55 and sigma = 15.26

I can just start to see some gaps
here it is as 1 pixel points
![image](https://user-images.githubusercontent.com/22768967/86927325-1ba87200-c12b-11ea-8779-fc8be6e0c260.png)

Quite sparse.

So here is a table of mean sigma and scale factor (that multiplies the width in pixels)

![image](https://user-images.githubusercontent.com/22768967/86929723-100a7a80-c12e-11ea-8fdc-650246d608c1.png)
 

I did a x 1000 and a x 10000 as well since I was having fun. The x10000 took a long time and put a big load on my pc. The main issue is probably in loading nearly 2million points intot he svg dom on the browser. I don't think your ipad would cope ;)  (it has used up about 14GB of RAM I estimate.)
![image](https://user-images.githubusercontent.com/22768967/86929514-d76aa100-c12d-11ea-82c9-428ae8eabf30.png)

I'm amazed how many points you need to get some consistency here and I don't think the party is over yet. (Of course maybe I've done something incorrect in my algorithm?)

**Comment by gfmoore** [comment]
I've set it to 10 x width for now to see how this pans out (down from 50 x width) let me know :)
Edit: No I've set it to 20 x width, too many holes with 10 x.

**Comment by gdcumming** [comment]
0.3.44

I'd say the fill is now perfect. Not slow. Looks good for all shapes. Copes with custom that takes up most of the display area, or only a tiny bit. Remarkably good!

Maybe one thing to check: Is the curve displayed in front of the fill dots in all cases? For max skew it looks like the dots (circles) are in front of the very steep part of the curve.

I'm happy if you close...

**Comment by gfmoore** [comment]
Well spotted. I thought I'd solved this (I had for sd lines, , but I think I have now for redrawing the curve! 
Sadly though this now shows that the fill isn't that good. I need to rethink how to decide if to draw a bubble, the maths I've used simply isn't good enough.

**Comment by gdcumming** [comment]
I don't follow. I'd be very happy to live with the fill as it is. The steep vertical of a high-skew curve is the only slightly iffy fit. If you can bring that curve in front of the circles it would have to be even better. I can't see why any further fill tweaks would be needed?

**Comment by gfmoore** [comment]
I've introduced another bug on fill when draw custom is too fast. Will deal with it asap.

**Comment by gdcumming** [comment]
0.3.48

Ah I see--that's probably what I've just opened as a new issue #25. Even with slow draw of custom, fill is not great at the L and R edges.

**Comment by gfmoore** [comment]
Okay, so yet another algorithm! The reason the last algorithm failed was that drawing a custom curve didn't provide enough points in the pdf array to compare against. The new one actually look pretty good.
This is a vary interesting problem in computer graphics. How can you determine if a line represented by dots is inside the bounds of a circle! I basically look at the bubble - radius and find the height of the pdf there and the same to the right and I compare these heights with the height of the bubble centre + radius. I also have to process the left and right rises especially for rectangular and custom. I do hope I don't have to change it again :)
This caused (as if it wouldn't) an issue with the rectangular pdf, as now instead of just using 6 points I had to create an array of points so that I could test the bubble against. Then I discovered an issue with scaling the height of the rectangle and on and on...

I think I'm only calling the create bubbles and draw bubbles as minimum as it should.

Anyway, how is it?  I do test, but seem to keep missing stuff that you find!!!

**Comment by gdcumming** [comment]
0.3.55

I sort of understand. Does this mean that it would make sense to use a different fill algorithm for the different curves? Esp. the rectangular and custom? Would that actually be simpler, even tho' it means >1 algorithm? I did say for #14 that the previous fill was excellent for all of normal, rectangular, and skew (except, being picky, for skew of 0.1--can ignore). So, would it make sense to stick with that old strategy for those 3, and find whatever's best for custom--alas, this new algorithm gives steps of circles when curve has a sloping top--try a triangular draw.

I get what you are saying about points in the pdf and circles of a particular radius. But I don't know enough to make any confident suggestions. Interpolate (linearly) between adjacent pdf points to fill in the custom curve line a bit? Or do this if the total number of pdf points is below some desirable minimum? Or any two adjacent points are more than some (horizontal) distance apart?

**Comment by gfmoore** [comment]
I will try to remedy this by re-instating part of my previous fill algorithm that uses Pythagoras' theorem, but I need to leave this program for a few days now.

I'm sorry, but this whole program has become far too complex for me to deal with. I am at my limit here and it is ceasing to become fun. Every change involves a huge amount of code tracing and I cannot see the trees anymore or keep in my mind all the variables and possible permutations of what will occur. 

I wrote the first demonstration in a week, on 15 May. Its now nearly 15 July!

I really want to move on to the next things. So can we have a think now about what is critical and what we can leave. Please.

**Comment by gdcumming** [comment]
0.3.60

I totally understand, thanks for your restraint, as well as great work to date. My apologies. I commented about fill as I closed #14

Let's close this one too.

**Comment by gfmoore** [comment]
No, I want to sort this one out. I've invested to much thinking to let it beat me. I only have to concentrate on the one portion of code, one method. 

There's no need to apologise, you haven't done anything wrong :)

**Comment by gfmoore** [comment]
I think? I've solved this.

I decided that though it would be slow, that for each bubble, I should check every coordinate in the pfd against it and if any coordinate was inside the bubble, don't draw it. I figured that there might be some optimisations I could do. This of course means there are a lot of bubbles nowhere near the pdf edge. If you have any ideas on how I can ignore these bubbles...

Sweet, except for custom where I had to tweak the top. This was because if the user draws too fast there aren't actually enough points near to the bubble under consideration. So in the drawing custom routing I did a linear interpolation for each pixel between the old mouse position and the new mouse position to add in the extra points.

To my utter astonishment this works and it seems to work really fast, even without any optimisations. Not that I cn think of any.

Hopefully, we can close this issue?

I have to say I'm feeling quite pleased with myself ;)

**Comment by gfmoore** [comment]
Spoke too soon, what a surprise. skew 0.1 has a few bubbles at top. Can't understand why? Perhaps I need more points here too.

**Comment by gfmoore** [comment]
Added extra points to skew pdf. A bit slower, but I can't see any fills above top. Maybe you can on larger screen? Please let me know there are now some tweaks I can apply.

**Comment by gdcumming** [comment]
0.3.64

Normal: perfect
Skew: perfect (for every level of skew!)
Rectangular: bubbles poke through top a bit, I think at every SD value.
Custom: I had to try hard to trick it. Steep slopes up or (more often) down often--but far from always--have bubbles poking through a little. But as it is now is perfectly usable. A very good satisfice.

![CIj fill 16 Jul 20](https://user-images.githubusercontent.com/55268816/87611169-afd99100-c74a-11ea-87ab-a77bba197867.png)

**Comment by gfmoore** [comment]
I've just had a brilliant? thought on this, though I don't know how to do it. I wonder if it is possible to simply mask out anything above the curve with a white fill? It would certainly just kill the need to do any calculations. Or draw a curve with a white shadow?

**Comment by gdcumming** [comment]
0.3.64

I don't know enough to have an opinion about brilliant or not--tho' it's clearly a couple of lateral thoughts, so potentially they suggest a different or additional approach.

My guess is that the (small) issue with rectangular would be fixed with some tweak to the distance standard, or tolerance limit, or something, for the vertical height allowed above fill bubbles. I think the issue is only with the top, not the L or R sides. So a tweak of your existing algorithm may be best.

For skew, one possibility is to have (for this case only) a solid blue line that's twice the width, thus allowing more leeway for circle placement. It might be ideal (as you suggest) if there is some way to have a white stripe (shadow) on the outside only of the blue line, but that may be a very tricky and sledgehammer solution, even if possible.

Overall, the custom fill issue is a very small one, the only small glitches appearing, I think, on steep up or down slopes. In my rough experiments, the speed of drawing such slopes doesn't seem to have any effect on the extent of the glitch--the number of circles that poke through or the amount they poke by. Which suggests it's not an issue of having too few points defining the line. Definitely don't lose sleep about this.

**Comment by gfmoore** [comment]
I added a tweak for rectangular. It worked first value I tried (which surprised me very much!) Hope I got it right.
Leaving others for now. I haven't done anything else with my bright idea - yet. I'll leave things as they are for now.

**Comment by gdcumming** [comment]
0.3.67

Alas, rectangular on my screen is now different, but not fixed. Circles always poke a bit above the top. For just some sigma values (e.g. 7, 10, 11, 22, 26) there is a blank stripe at L and R ends inside the rectangle. Pic below is sigma=11

![CIj fill 19 Jul 20](https://user-images.githubusercontent.com/55268816/87864037-46ee5500-c9a6-11ea-8bf9-fe2676474e53.png)

**Comment by gfmoore** [comment]
I knew it was too good to be true!!!

I removed my fix, but did find an error for the sides. I rarely see the bubbles at the top, but then I'm only using a small screen. 

I'll have another look at it soon.

**Comment by gdcumming** [comment]
0.3.68

I'm seeing the same, I think, as 0.3.67 yesterday, as in pic above--small poking above top, and same side issue at the same sigma values.

**Comment by gfmoore** [comment]
So, eventually I spotted two errors. a second declaration of a flag variable that made it too local, and worse a spelling error between drawit and drawIt.  More beginners errors. Like I tell my students, most of your programming errors are spelling errors. Of course it's much harder for them not being native English speakers. JavaScript is a very forgiving language, too forgiving. Java would have picked up the spelling error.

I hope it's fixed.

I know that custom can occasionally have bubbles poking through on steep sides, but I have no clue how to solve this. I will look into my "bright" idea, but not just yet. Can it satisfice?

**Comment by gdcumming** [comment]
0.3.70

Rectangular: Top looks good-well done. Still have the narrow blank areas at sides, at least for some sigma values, as before.

Let's satisfice this. I'm sure it won't impact anyone's learning, and that's our basic game.

**Comment by gfmoore** [comment]
There are some things to satisfice on, but I don't think this isn't one of them :)
That was an odd one to figure out. I was looking in entirely the wrong place, i.e. my fill algorithm. The problem went back much further in the actual creation of the pdf itself. I had used 100 points figuring that would be plenty for such a well behaved function. However, when it came to deciding if a bubble should be displayed there was not enough resolution, working at a real coordinate level of 1 to 100 which meant that the number of pixels would be too much and hence a gap - occasionally, depending on the user screen size etc.
Anyway now using a thousand points and seems better on my screen, but I'll leave it to you to test on bigger screens.

**Comment by gdcumming** [comment]
0.9.4 Beta

Hooray! Success with rectangular! So normal, rectangular, skew all have *perfect* fill. 

Custom is good, with only the occasional very steep line having a bit of circles peeking a tiny bit. Satisfice here, it really is a *very* minor issue.

With the new larger numbers on top axis, maybe the top axis has shifted down a tiny bit. Rectangular with very small sigma pokes up a tiny bit above that axis. Unless that's very easy to adjust, don't touch it. It's an even more minor issue!

**Comment by gfmoore** [comment]
As per dance of p values comment
