### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#23]
0.3.42

Bob's suggestion. Let's have some more things turned on, when ESCI-JS is downloaded or opened. So that clicking for a sample, or Run, leads to something happening on screen.

I suggest:

Panel 1--as now

Panel 2--Population and fill on

Panel 4--all three checkboxes on

Panel 5--just Mean Heap on

Panel 6--CIs off, as now

Panel 7--just mu line on

Panels 8, 9--nothing on, as now

Happy to discuss a different pattern of choices.

**Comment by gfmoore** [comment]
Implemented. (I had almost all of these already set up for when I'm developing/testing, so just had to keep uncommented.)

**Comment by gdcumming** [comment]
Great. Thanks. Closing...
