### ISSUE TITLE
Scroll in left hand rectangle

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#26]
0.3.48

On my computer screen I see H and V scroll bars in LH display rectangle (where the Panels 1-9 are.) I think they came in as a byproduct of work on tablets.

I suggest as part of prioritising laptop and desktop you remove these scroll bars, even if that decreases the flexibility for tablet and phone. Hoping that's not too hard, even if in some ways it may be a step backwards.

**Comment by gfmoore** [comment]
Should be done. Of course the surface (and now most laptops) are touchable!
I don't know why the horizontal scroll appeared though, I didn't enable it.

As per usual mine is perfect! lol
![image](https://user-images.githubusercontent.com/22768967/87252550-e7ef8400-c46b-11ea-8b59-fd29b689103b.png)

**Comment by gdcumming** [comment]
0.3.55

Perfect, thanks, closing
