### ISSUE TITLE
Displaying mean and sd of Latest sample

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#28]
0.9.9 Beta

In Panel 4, if Dropping means is ON, then Sample means must also be ON, and we can see the M and s values for the Latest sample. That's all great.

But if Dropping means is OFF and Sample means is ON, then we don't see that M and s for the Latest sample. It would be great to have M and s values displayed whenever Sample means is ON (and a sample has been taken).

No urgency, and not a disaster to live with what we have, if fixing this would be a nightmare.

**Comment by gfmoore** [comment]
Tricky, but I think I've managed it. However, you'll need to QA it thoroughly again to make sure I haven't introduced any side effects. It looks ok to me, but I don't seem to be that good a tester!!

**Comment by gdcumming** [comment]
0.9.10
I think you have nailed it, thanks.
