### ISSUE TITLE
Popouts, comments, tool tips

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#3]
ESCI used Excel’s comments (now called ‘notes’): hover on little red triangle and see brief definition or explanation. ‘’Tool tips’ are similar, in Office: hover over any icon on the ribbon to see, after a short delay, the popout text. Does JavaScript offer any such option?

Having some sort of popouts means that labels, etc, on screen can be briefer. Ideally, popouts could apply to checkboxes, reported values, … anything else, and not just to labels.

It’s really handy to be able to check version number by clicking on logo, top left. Could this be hover rather than click?

**Comment by gfmoore** [comment]
Para 3, This has been changed,

**Comment by gdcumming** [comment]
Thanks, nice.

**Comment by gfmoore** [comment]
So that turned out to be a little more work than expected. Mainly because when I tested on a tablet I didn't remember that browsers keep caching and I was testing on an unchanged old version. I had to keep clearing the cache - which is a pain to find.
Same issue on a laptop - but at least there is the shift-refresh trick.

Anyhow, because there is no concept of hover on a tablet/phone I added back in the click function to turn the dialog off when clicked.

**Comment by gfmoore** [comment]
Oh and just a thought, I think I will always update the New Statistics version of ESCI-JS before my own server version, so don't rely on my server version being up to date. It seems silly to have to update two sites when only one is needed. :)

**Comment by gfmoore** [comment]
I'm giving some consideration to implementing tooltips in the interface.
On a laptop/desktop no issue as there are libraries which implement the tooltip appearing on hover.
Tablets and phones are a little different as we saw on the Version dialog issue.

The thing is that though you can register a touch event (as I did) it might cause a few issues with small screens as it will be quite easy to accidentally touch he wrong thing and that could be annoying.

As an example think about touching/hovering over the mu in the first panel, on a laptop no problem, you get a tooltip and it disappear. But on the touchscreen it will be easy to touch the slider itself.

There is no UI principle for these devices that I've found, in fact often it is suggested that a different approach should be taken.

Any thoughts on this issue?

**Comment by gfmoore** [comment]
[https://stackoverflow.com/questions/1737773/tooltips-in-the-era-of-touch]

**Comment by gfmoore** [comment]
I've added the tooltips from ESCI. I'm not at all happy with how they are working and in particular having tooltips on buttons isn't a good look so currently disabled. 
Anyhow at least I've gone through the process of grabbing the text from ESCI :)

**Comment by gdcumming** [comment]
Very interesting to play with the .10 version with popouts. Well done to get it working! On the one hand, it's great to see what's possible, and I'm sure they are helpful and informative. But so easily they can be too much, not at the right time or place, and annoying. I suspect it's a matter of fine detail. It may be best if there is a 0.5 or 0.7 sec (or something) delay from hover over item until popout appears, as in Office. Then it disappears immediately on click or mouse move. At present they can easily appear at some place the mouse swept past a moment earlier. The version number popout appears erratic--sometimes flashing on and off for a while even after the mouse has moved on. 

Eventually, the text in many needs tight editing, and/or adjustment to fit your -JS version. (My verbosity! I could work on that in due course.) Maybe larger font.

Unless easy to tweak, having popouts (that work well) may be lower priority?

It looks like this is one more area in which phones and tablets need to work differently. One more reason not to worry about them at present? An app might or might not be a possibility later.

**Comment by gfmoore** [comment]
I'll have a look at adding  delay. I know what you mean about the version dialog now playing up - most annoying.

However, based on a suggestion in the link and to stop it annoying me so much, I added a button at top right to turn tooltips on or off, default is off!

As you say, this is a low priority, but I thought it would be an easy toto - it wasn't. :)

**Comment by gfmoore** [comment]
Ok so I need to spend serious time looking at the tablet. The hover on version number proved to be highly irritating and flaky. What seemed to happen is that you move the mouse over the icon, it triggers the mouseenter event and the appearance of the dialog, but if you move the mouse off the browser then it doesn't get the mouseleave event, so the dialog stays.
For now and because I wanted to concentrate on some basic functionality I reverted this back to click on, click off. I also removed the touch events as they weren't playing right either. I will sort this, but let me clear up some of the longstanding issues first.

Man you'd have thought this was the easiest issue to sort out :)

There's 2200 lines of code in this thing and on a small screen I'm losing my way around :()

**Comment by gdcumming** [comment]
Click on and off for version number is fine, at least for the moment. Happy to put this issue on the back burner. When everything else is finalised (!) I can edit the text of the popouts.

**Comment by gfmoore** [comment]
Okay, I'm going to investigate some third party popup mechanisms.
However, I will need a list of every comment for exactly which control or value please. So:

fieldname/valuebox   comment

Thanks.

**Comment by gfmoore** [comment]
2020-07-15  CI$3  Used a tooltip library - Tipped - to enhance tooltips.

Can't say I'm totally enamoured. However, Styles can be changed, e.g. size, colour etc. There may be a better library. At least it restores the hover to the version dialog.

**Comment by gdcumming** [comment]
0.3.64

Wow, so easy to read!

This is fine, indeed very good, for now. I'll work on the text, as requested, tho' probably not for a little while.

In the meantime, a question for my info: can this system insert a delay before a tip becomes visible? It has always struck me that the key component of a popout system is that it can be lurking in the background, never intruding except when needed, which is when a user pauses to wonder. Then, magically, the answer to the pondering pops up, after 0.5 sec (or something)!

It's a bonus that ours can be turned on or off so easily.

**Comment by gdcumming** [comment]
Just noticed that when tips turned off, the tip still displays for the CIs checkbox, Panel 6. I think this is the only one. (It's good that the version no. and tip on the switch for tips (top right) don't turn off.)

**Comment by gfmoore** [comment]
Nope, it was more than one. I hope I've not got them all, pesky things!!!

btw, I've tried out quite a few libraries and though a few are more sophisticated, the one I use (tipped) seems to be the one that does what we need with the minimum of effort. I had hoped that the content could be formatted a little (maybe they can and I just haven't figured it out yet), but the one that could was very clunky and complicated to use and I just gave up on it.

Let me know if you want the style changed, it can be done.

**Comment by gfmoore** [comment]
In the meantime, a question for my info: can this system insert a delay before a tip becomes visible? It has always struck me that the key component of a popout system is that it can be lurking in the background, never intruding except when needed, which is when a user pauses to wonder. Then, magically, the answer to the pondering pops up, after 0.5 sec (or something)!

>> yes a delay is possible, let me know if you want it and for how long. :) (Probably version should be a lot quicker?)

**Comment by gfmoore** [comment]
I'm thinking that I should probably indent your comments when answering and leave mine at higher level! I shall do that from now on :)

**Comment by gdcumming** [comment]
0.3.67

I suspect we'll need to suck it and see with delay. I suggest starting with 0.7 sec. Yes, let's have version number immediate.

On my todo list: revised spec for popouts, incl. text

**Comment by gfmoore** [comment]
Okay so I've set to 750ms, which still seems quite quick. If you hover over 'esci-web' that takes 1500ms. Don't forget to click on ?

**Comment by gfmoore** [comment]
I mean on esci-web header

**Comment by gdcumming** [comment]
0.3.68

I like the delay, thanks. Let's leave it as is until I get back to you with spec+text, maybe today or tomorrow.

Can you tell me what scope you have for style changes, e.g. slightly smaller font in tips, much smaller balloon, i.e. much less blank space above and below text? Scope to say where the angular pointer bit is positioned on the balloon border? I.e. to specify what it points to?

Do you freedom to set when balloon goes off, maybe in terms of where the mouse moves? (At present it seems necessary to move the mouse a fair way before balloon disappears.)

I'm not trying to set up a highly complex editing task--just wanting to know what you can set easily in an overall way.

**Comment by gfmoore** [comment]
https://atomiks.github.io/tippyjs/

Should give you some ideas :)

⁣Regards,

Gordon Moore
gm@gordonmoore.co.uk​

**Comment by gfmoore** [comment]
Oops wrong website I use tipped!! https://www.tippedjs.com/documentation/options 
Anyway I think I've implemented what you asked, though you may want a different font size and padding. 

I think I've done the correct selections. Did require some refactoring, I hope I didn't break anything.

**Comment by gdcumming** [comment]
0.9.4 Beta

Love them--they work so much better, being more compact and with, I think, tighter active areas around labels, etc. I like the shifting with the mouse--they seem more responsive and local.

It's great to have Greek letters.

Is it possible to have slightly larger font in the tips? Not as large as before, preferably with minimum enlargement of the tip area. (I know, I'm never satisfied...)

Missing tip, Panel 6, line 2: Use dropdown to select confidence level

Tip for sigma known: $sigma; --wrong code to give Greek sigma?

Panel 7, line 1: the mu is shown as a square

**Comment by gfmoore** [comment]
All done - I hope.

**Comment by gfmoore** [comment]
As per dance of p values comment
