### ISSUE TITLE
Tweaks to display

### ISSUE THREAD

**Issue by gfmoore** [gfmoore/ESCI-JS#30]
Shift of the L border so the label can go outside-which is great.

Clicking off the p value: I hadn't thought to ask for reversion to mu = 50. I guess that would be nice, tho' not a big deal. No need to worry about SD lines on the population.

If you are up for any further tweaking, please add X (italic, bold, a little larger than the numbers) to the top and bottom axes, a bit left of '50'. They could be positioned as in Figs 4.6, 4.7, etc in the revised version of Chap 4 I sent recently. But now you have made a bit more space at the bottom (for the mu and mu0 labels) perhaps the lower 'X' could drop down a bit.

Totally optional extra, ONLY if easy and safe:
tweak the right hand end of the axes so we can see '100' in full. Maybe just shift that number a whisker left? Or...?
Give us a *little* more space above the top axis, so the 'X' can be a bit higher than the numbers on that axis. But only a bit.

I'm really not too worried if those last two (or even all the outrageous requests herein) don't get done!

**Comment by gfmoore** [comment]
Shifted left axis in a little.

On clicking of p value mean reverts to 50. 

X's positioned.

Adjusted 100 label a bit. I can't get it to display in the right hand edge as that isn't part of the displayable area. Bad design decision at start and now I daren't change anything!!! I'll keep it in my mind and maybe do a test version.

**Comment by gdcumming** [comment]
0.9.12 Beta

On 1 minute's testing that all looks great. Thanks. Don't touch a thing!
