### ISSUE TITLE
Count of captures when no dropping means

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#31]
0.9.12 Beta

When Sample means ON and Dropping means OFF, then Panel 4 'number of samples' and Panel 7 'Samples taken' do not count up from zero as samples are taken. That's correct.

But, if CIs and Capture of mu are both ON, then 'Number capturing mu' *does* count up. In fact even if CIs and/or Capture of mu are OFF, that count does continue but is not displayed. Click those two ON and a higher count is displayed.

'Dropping means' ON should be required for count of 'Capture of mu' (as well as the counts of total samples taken) to proceed.

This is not terrible. We could live with it.

**Comment by gfmoore** [comment]
ok, btw are you registered to receive notifications on d pictures as I did upload a new version yesterday?


regards,

Gordon Moore
gm@gordonmoore.co.uk

On 18/08/2020 08:17:18, Geoff Cumming <notifications@github.com> wrote:
0.9.12 Beta
When Sample means ON and Dropping means OFF, then Panel 4 'number of samples' and Panel 7 'Samples taken' do not count up from zero as samples are taken. That's correct.
But, if CIs and Capture of mu are both ON, then 'Number capturing mu' does count up. In fact even if CIs and/or Capture of mu are OFF, that count does continue but is not displayed. Click those two ON and a higher count is displayed.
'Dropping means' ON should be required for count of 'Capture of mu' (as well as the counts of total samples taken) to proceed.
This is not terrible. We could live with it.

**Comment by gdcumming** [comment]
Hi Gordon,

Sure am!

I was just about to enthuse about d picture. So cool! Thanks!

I thought I'd just enter those other pesky issues so you wouldn't have so much boring old free time on your hands (!)--if it is actually feasible to fix them.

More soon on d picture. I don't expect there will be much, but I'll check the calcs.

Geoff

--------------------------------------------
Geoff Cumming, DPhil, Emeritus Professor,
School of Psychology and Public Health, La Trobe University, Melbourne Campus, Victoria, Australia 3086
Email: g.cumming@latrobe.edu.au<mailto:g.cumming@latrobe.edu.au>
Intro textbook: Introduction to The New Statistics: Estimation, Open Science, and Beyond    www.thenewstatistics.com<http://www.thenewstatistics.com>
First book: Understanding The New Statistics: Effect Sizes, Confidence Intervals, and Meta-Analysis   ww.thenewstatistics.com<http://www.thenewstatistics.com/>
Own page: http://www.latrobe.edu.au/she/contact-us/staff/profile?uname=GDCumming
ESCI (Exploratory Software for Confidence Intervals):  www.thenewstatistics.com<http://www.thenewstatistics.com/>
Introduction to the New Statistics is the first statistics textbook to focus on Open Science and the New Statistics. Instructors can obtain a free desk copy at https://www.routledge.com/resources/deskcopy.
Order on Amazon <http://www.amazon.com/dp/1138825522>
[1464879986726_ITNS]


________________________________

**Comment by gfmoore** [comment]
What does this look like. I added an extra flag for the display. (When changing dropping means it clears everything (should).

**Comment by gdcumming** [comment]
0.9.14 Beta

Looks good. Thanks. Closing.
