### ISSUE TITLE
Capture %ages more than 100

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#32]
0.9.12 Beta

I don't know whether this (and the other issue I've just created) are long-standing, or recent arrivals.

I think this issue arises only when Mean Heap is ON.

Take a run of samples. Stop. Make a change (change from Known to Unknown or v.v., or CIs on/off, or Capture of mu on/off) then take one or two samples, or another run. See, often, that 'Percent capturing mu' is suddenly way above 100, and, correspondingly, 'Number capturing mu' is way higher than 'Samples taken'.

I haven't been able to pin down exactly what combination or sequence of changes is necessary and sufficient for the issue to emerge. Do a run, make a change, take even only 1 or 2 samples--it often happens.

If sampling is running and Known/Unknown is changed the % suddenly jumps above 100.

Panel 8 (capture of next mean) doesn't seem to have the problem with its counting of captures of next mean.

The problem seems to happen whether or not Panel 8 is on or off, and whether or not Panel 9 is on or off.

**Comment by gfmoore** [comment]
Okay, so I checked the code and found that occasionally the recalculation was also recounting the means in the heap at times. I am not sure if there was a reason for this. I can't think of one. So I removed the extra code. But we need to be on the look out for any unintended consequences...

**Comment by gdcumming** [comment]
0.9.14 Beta

Alas, still an issue. Seems different now. I've seen c. 2500%, and I wasn't taking long runs. Now it happens whether or not Mean heap is on. The critical step seems to be to turn Dropping means ON.

The shortest and simplest way I've found to generate the problem is: with Dropping means OFF, do Clear. Take a sample. Turn Dropping means ON. Change Known/Unknown. Take a sample, see 200%. All those steps seem necessary.

With Dropping means left ON, I don't think I've seen the problem, which suggests that we could live with it if we need to.

I don't think it would be a problem if turning Dropping means ON did a Stop&Clear.

**Comment by gfmoore** [comment]
I'm sure you must think I don't test what I do, obviously though I don't test enough!! :(

Okay, so there are only two places where the capture count gets updated and I noted that one of these shouldn't be updating given the conditions. Also when I reset the capture stats I never cleared the array - it was cleared elsewhere, but not general enough with all the new conditions. I've refactored and tested! It looks good. Drop now stops and clears when turned on or off, although it basically did this, but now made certain.

Over to you for full QA. ;)

**Comment by gdcumming** [comment]
0.9.17 Beta

Lots of things work well and look very nice. I can't see anything obviously linked to the latest issues. Good.

But I did come across two issues. I'm pretty sure they are both new, or recent.

!. Set dropping means, CIs, capture of mu, mean heap all ON. Take samples. Mean heap builds, with red means piling up in the tails as they should. Capture % looks to be correct. If sigma Known, the red dots are neatly in the tails. If Unknown, red is a bit more scattered, esp. if N is very small. That's all correct and good. Now change Known/Unknown and see all red disappear from the mean heap (not from the dropping means). Continue sampling and the capture % still seems correct (i.e. the means that were red, now green, are still counted as non-captures), red means drop and remain red in the heap. This disappearance of red from the heap happens whatever the population shape, and whether Known/Unknown is changed while sampling is stopped, or is still running.

2. A return of a version of an old issue. Set mu = 50 and sigma = 20 (or more) and N = small, capture of mu ON and MoE lines visible. Take samples and watch red means as they hit the heap--they take a distinct jump outward, to the left into the left tail, to the right into the right tail. If sigma Known, there is one or one-and-a-half columns of green dots on the outside of the MoE lines. Try the same with mu = 10 or 20, sigma small, and see the whole mean heap (peak and tails) shifted left relative to the mu line and MoE lines. With mu = 80 or 90, the heap is shifted right relative to those lines. The outward shift can be up to two dot widths. Happens whatever the population shape.

**Comment by gfmoore** [comment]
The first issue was because in sorting out the count issue I commented out some code that didn't make sense. I've restored this and removed the actual code that was not required in the count part - silly me.

The second issue (and perhaps should really have been a separate issue??) was more concerning. After spending a couple of hours on it I suddenly realised that this was an unintended consequence of moving the margin to allow the label on the outside. I knew there would be problems from this. I have reverted the code to what it was. Fortunately I made a detailed note of exactly what I had changed so this was quite straightforward.

 I'm sorry, but I wasn't prepared to spend many hours trying to figure this out and perhaps also introduce more issues that I could not foresee. I spent many many hours trying to get the code right and I really don't want to go down that rabbit hole again. Blame it on my poor programming skills and design skills, but as I've said before this code is now so complex for me that I can hardly follow it all.

With sadness it will have to suffice. 

I'm afraid you will now have to go through the QA again to make sure nothing else has been affected by what I've done, redone.

**Comment by gfmoore** [comment]
I thought I'd had a brilliant idea of creating a narrow strip of white between the two panels and putting the label there. Unfortunately the calculations for getting the width if the display area especially when resizing are not trivial (they should be, but there are strange bugs in getting proper widths of elements in browsers.) So things started going wrong again. Getting a border around the new area of two areas also proved non-trivial. Life was so much easier in the days of absolute positioning...e.g. visual basic and turbo Pascal. Oh for the days of MS-Dos.

**Comment by gdcumming** [comment]
0.9.18 Beta

That's so reminiscent of what I experienced over and over with Excel, years back. Think of some neat possible solution, usually in the small hours, next day eagerly try it out only to discover that one or more other things don't respond in sensible ways. I was pushing Charts beyond their limit, with quite a few online folks giving advice, so we could do neat interactive things beyond what was in the MS spec. Fine. Except that next version of Excel, supposedly fully back-compatible, simply wasn't and it was back to the drawing board, or just give up on some neat things. 2007 was definitely the time to move on from Excel.

Anyway, this reverted version looks very good to me. I'm going to make a new issue of one little thing, but it's not a big deal--a bit obscure. There's a point beyond which if a user does a whole sequence of strange things then they are on their own. All they need to do is Clear to get back on an even keel.

I know I go on about it, maybe tediously, but it does work so well and look so good. Mean heap growing neatly, dramatic and sensible changes with click between sigma known and unknown, change in C value, etc, etc. Plus capture of next mean. Plus dance of the p values. So good!
