### ISSUE TITLE
Turning on stuff when Panel 9 ON

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#35]
0.9.18 Beta

When Panel 9 is clicked ON, everything is tidied up and we're set for dance of the p values. That's great.

But once Panel 9 is ON, the user can click various things on (or off). In most cases that I've tried that doesn't seem to lead to any problem. But if mean heap is turned ON, then samples taken, with sigma unknown, then the colour patches (left hand column) don't disappear for means that are in the heap. Or take samples with sigma known, see mean heap build, all is fine. Then switch to sigma unknown (either while sampling is running, or after stopping) and see colour patches bottom left (that must have corresponded with some means in the heap). Sample more and bottom left is a bit of a colour patch mess.

Options:
1. Do nothing. This is an obscure thing, and we could easily satisfice by doing nothing. 
2. Tweak the colour patch display code, when sigma unknown, so patches disappear when they should, i.e. for means that have landed on the heap.
3. Disable the possibility of turning mean heap on, when Panel 9 is on. This may be the best solution, if easily and safely doable. If so, consider making it similarly impossible to turn Panel 8 on when Panel 9 is on. (That doesn't seem to lead to anything wrong or misleading, just to a strange combination of two perfectly good demos--mean capture and p values.) But only if easy and safe to do.

**Comment by gfmoore** [comment]
Option 3 seemed the easiest to do. Also added don't allow p values if capture next mean on, i.e. if panel 8 on don't allow panel 9

**Comment by gdcumming** [comment]
0.9.19
Looks good to me. Closing.
