### ISSUE TITLE
Display of population

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#5]
Fill under pop curve. Let’s have the multiple circles under the pop curve each the same as the circles for the data points in the latest sample? Therefore stronger outline colour for the fill circles, and no colour fill of the data points? 

Sometimes there seems to be a tiny stripe of spacing above the heap of fill circles and under the curve, as if they could be stacked a tiny bit higher. Especially for large pop SD.

Switch between normal and rectangular: If ‘Fill Random’ is on, the fill pattern doesn’t switch to match the new pop shape. 

Click pop curve off, and still see the pile of fill circles. This should probably be displayed only when pop curve is visible.

Height adjustment of the pop curve, with change in pop SD. This doesn’t work exactly as in ESCI, but seems to be OK.

**Comment by gfmoore** [comment]
Fixed the switching issue, Hope that works now.

Also fill bubbles should disappear as well.

So TODO, try and figure out a better "bubble" fill. 

Done the height adjustment as explained elsewhere, let me know what you think.

**Comment by gdcumming** [comment]
Switching seems fine. 

Bubble fit in rectangular: often get blank stripes down side.

Height adjustment--change sigma and see top of curve (normal or skew) change from low to way above top of display rectangle. I.e. not adjusting so height neatly fits just below top of display area.
