### ISSUE TITLE
Means 

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#6]
Dropping means

Vertical spacing is good.

Mean heap 

Stacking of means in the mean heap is now wonderful—neat H and V stacking, on all screens I’ve tried. Falling means now drop neatly onto the top of the appropriate column of the heap—great!

Scaling of the height of the curve to fit the mean heap: just those means that have arrived and are piled. This sometimes looks about right, other times seems way too high, with lots of blank space under curve above piled means; I haven’t been able to discover any regularity about when. On iPad and iPhone it seems better, but I’m not sure.

**Comment by gfmoore** [comment]
So the heap fitting curve, sampling curve is based on the mean of the mean heap (the sampling means distribution) and on the standard error as calculated using N and the standard deviation of the mean heap.

So the mean heap is an array of objects, i.e. an array containing the x value of each dropping mean.
I find the mean and sd of that. Actually I update these variables every time I generate a new mean. Some pretty clever maths that someone worked out. Saves having to recalculate afresh from all values everytime a new sampling mean is created. 

Not saying that it is actually any better though!!

Perhaps I need to check the calculations.

Again, what approach did you take in the spreadsheet?

**Comment by gdcumming** [comment]
To report the 'mean heap SE' (cf. 'curve SE' which is based on known pop sigma) I keep a record of means in the heap and calculate SD of those. I'm suggesting you also could report the 'mean heap mean', which would be the mean of those means in the heap. (Your fancy running recalc of mean and SD could give you those values; I simply use Excel's automatic recalc of the spreadsheet after every new sample is taken.)

The curve on the mean heap is a different beast, and much simpler, because it's meant to be what we'd expect theoretically, given known mu, sigma, and assuming normal distribution. So it should not bounce around as more samples are taken.

Only the height of that curve needs to be adjusted dynamically as more means are dropped onto the heap. To calc the height required, I calc what area we need under that curve to be equal to the area (little squares, one for each mean, with sides equal to the diam of the dot representing a mean)  of the number of means in the heap. It should grow fractionally for each new mean piling onto the heap. 

With normal pop, the curve and the heap of means should approx match, in that the columns of dots sticking up above the curve should, by eyeball, roughly balance the columns of dots that don't reach up to the curve. At present it seems to me that curve height is often about right, but sometimes seems distinctly too high for the number of dots in the heap. As I said, I can't find any regularity to assist in diagnosis.

For non-normal pop, I still calc the curve the same way, using mu and sigma of the pop. So the curve is always in the shape of a normal distribution, and tells us what the heap should look like, if the central limit theorem's limiting case applies for the current N. It's dramatic to see how closely the mean heap approximates that expected smooth normal distribution curve, except when the pop is strongly skewed AND N is small.
